apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine-pad
spec:
  selector:
    matchLabels:
      app: alpine-pad
  template:
    metadata:
      labels:
        app: alpine-pad
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
        - sleep
        - "3600"
        volumeMounts:
        - name: hostfs
          mountPath: /hostfs
      volumes:
      - name: hostfs
        hostPath:
          path: /